//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ltc_dbEntities : DbContext
    {
        public ltc_dbEntities()
            : base("name=ltc_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login_record> login_record { get; set; }
        public virtual DbSet<login_users> login_users { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<patient_basic_info> patient_basic_info { get; set; }
        public virtual DbSet<patient_contacts> patient_contacts { get; set; }
    }
}
