//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_contacts
    {
        public int sn { get; set; }
        public int patient_sn { get; set; }
        public string contacts { get; set; }
        public string relationship { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string cellphone { get; set; }
    }
}
